"""Pandera schemas for generated data-pipeline artifacts."""

import pandera.pandas as pa

WAVES = ["IFLS4", "IFLS5"]
BINARY = [0, 1]


def _wave_column() -> pa.Column:
    return pa.Column(str, checks=pa.Check.isin(WAVES), nullable=False, coerce=True)


def _id_column() -> pa.Column:
    return pa.Column(str, nullable=False, coerce=True)


def _binary_column(*, nullable: bool = False) -> pa.Column:
    return pa.Column(
        int,
        checks=pa.Check.isin(BINARY),
        nullable=nullable,
        coerce=True,
    )


def _schema_columns(
    schema: pa.DataFrameSchema, names: list[str]
) -> dict[str, pa.Column]:
    return {name: schema.columns[name] for name in names}


# Generated by code/data/01_extract_individuals.py -> data/generated/individuals.parquet
# Row level: one person-wave interview record, keyed by pidlink + wave.
INDIVIDUALS_SCHEMA = pa.DataFrameSchema(
    {
        # Stable IFLS person identifier, used as the person-level merge key.
        "pidlink": _id_column(),
        # Wave-specific household identifier used for household-level merges.
        "hhid": _id_column(),
        # Individual interview date built from the wave-specific cover/date fields.
        "interview_date": pa.Column(pa.DateTime, nullable=False, coerce=True),
        # BPS two-digit province code from the household screening file.
        "province_code": pa.Column(int, nullable=False, coerce=True),
        # BPS four-digit kabupaten code, computed as province*100 plus within-province kabupaten.
        "kabupaten_code": pa.Column(int, nullable=False, coerce=True),
        # BPS seven-digit kecamatan code, computed from kabupaten_code and within-kabupaten kecamatan.
        "kecamatan_code": pa.Column(int, nullable=False, coerce=True),
        # IFLS survey wave for the person record.
        "wave": _wave_column(),
    },
    strict=True,
    unique=["pidlink", "wave"],
)


# Generated by code/data/04_score_cesd.py -> data/generated/cesd_scores.parquet
# Row level: one person-wave CES-D score, keyed by pidlink + wave.
CESD_SCORES_SCHEMA = pa.DataFrameSchema(
    {
        # Stable IFLS person identifier, used as the person-level merge key.
        "pidlink": _id_column(),
        # IFLS survey wave that produced the mental-health record.
        "wave": _wave_column(),
        # Sum of CES-D-10 frequency scores after reverse-coding positive items.
        "cesd_raw": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        # IFLS4 screener count of endorsed CES-D items; missing for IFLS5.
        "cesd10_count": pa.Column(
            float, checks=pa.Check.between(0, 10), nullable=True, coerce=True
        ),
        # Indicator for CES-D raw score at or above the cutoff of 10.
        "depressed": _binary_column(),
        # Number of CES-D items contributing to the person-wave score.
        "n_items": pa.Column(
            int, checks=pa.Check.between(0, 10), nullable=False, coerce=True
        ),
        # CES-D factor scores and within-wave standardized versions.
        "somatic": pa.Column(float, checks=pa.Check.ge(0), nullable=False, coerce=True),
        # TODO: Add comments to data stuff below
        # TODO: Check why data is sometimes null
        "depraffect": pa.Column(
            float,
            checks=pa.Check.ge(0),
            coerce=True,
            nullable=True,
        ),
        # TODO: CHeck why data is sometimes null
        "posaffect": pa.Column(
            float,
            checks=pa.Check.ge(0),
            coerce=True,
            nullable=True,
        ),
        "somatic_z": pa.Column(float, nullable=False, coerce=True),
        # TODO: Add back null guard
        "depraffect_z": pa.Column(
            float,
            coerce=True,
            nullable=True,
        ),
        "posaffect_z": pa.Column(
            float,
            coerce=True,
            nullable=True,
        ),
    },
    strict=True,
    unique=["pidlink", "wave"],
)

# Generated by code/data/05_build_person_covariates.py -> data/generated/stressors.parquet
# Row level: one person-wave stressor/covariate record, keyed by pidlink + wave.
STRESSORS_SCHEMA = pa.DataFrameSchema(
    {
        # Stable IFLS person identifier, used as the person-level merge key.
        "pidlink": _id_column(),
        # Wave-specific household identifier used for household-level merges.
        "hhid": _id_column(),
        # Respondent age from the household roster after sentinel cleaning.
        "age": pa.Column(
            float, checks=pa.Check.between(0, 120), nullable=True, coerce=True
        ),
        # Respondent sex from the roster, normalized to F/M.
        "sex": pa.Column(
            str, checks=pa.Check.isin(["F", "M"]), nullable=False, coerce=True
        ),
        # Indicator for currently married marital status.
        "married": _binary_column(),
        # Indicator for widowed marital status.
        "widowed": _binary_column(),
        # Approximate years of schooling mapped from IFLS education level.
        "edu_yrs": pa.Column(int, checks=pa.Check.ge(0), nullable=False, coerce=True),
        # IFLS survey wave for the stressor/covariate record.
        "wave": _wave_column(),
        # Household size used in per-capita expenditure calculations.
        "hhsize": pa.Column(float, checks=pa.Check.ge(0), nullable=True, coerce=True),
        # Nominal monthly per-capita household expenditure.
        "pce": pa.Column(float, checks=pa.Check.ge(0), nullable=True, coerce=True),
        # Natural log of monthly per-capita expenditure.
        "pce_log": pa.Column(float, nullable=True, coerce=True),
        # Within-wave quintile of monthly per-capita expenditure.
        "pce_quintile": pa.Column(
            float, checks=pa.Check.between(1, 5), nullable=True, coerce=True
        ),
        # Household reported any natural disaster in the past 5 years.
        "disaster_5yr": _binary_column(),
        # Household reported a severe natural disaster in the past 5 years.
        "disaster_severe_5yr": _binary_column(),
        # Household had a loan application rejected.
        "loan_rejected": _binary_column(),
        # Respondent's primary job is in agriculture, forestry, or fishery.
        "agri_occupation": _binary_column(),
    },
    strict=True,
    unique=["pidlink", "wave"],
)

# Generated by code/data/10_fetch_temperature_gee.py -> data/generated/daily_temperature_kab.parquet
# Row level: one kabupaten-day weather record, keyed by kabupaten_code + date.
DAILY_TEMPERATURE_SCHEMA = pa.DataFrameSchema(
    {
        # BPS four-digit kabupaten code identifying the polygon.
        "kabupaten_code": pa.Column(int, nullable=False, coerce=True),
        # Calendar date of the daily ERA5-Land aggregate.
        "date": pa.Column(pa.DateTime, nullable=False, coerce=True),
        # Daily polygon-mean 2m air temperature in Celsius.
        "tmean_c": pa.Column(float, nullable=False, coerce=True),
        # Daily maximum 2m air temperature in Celsius.
        "tmax_c": pa.Column(float, nullable=False, coerce=True),
        # Daily minimum 2m air temperature in Celsius.
        "tmin_c": pa.Column(float, nullable=False, coerce=True),
        # Daily polygon-mean 2m dewpoint temperature in Celsius.
        "dewp_c": pa.Column(float, nullable=False, coerce=True),
        # Daily total precipitation in millimeters.
        # TODO: for some reason, precip_mm has negative values so remove for now
        "precip_mm": pa.Column(
            float,
            nullable=False,
            coerce=True,
            # checks=pa.Check.ge(0),
        ),
        # Relative humidity percentage derived from mean temperature and dewpoint.
        "rh_pct": pa.Column(
            float,
            nullable=False,
            coerce=True,
            checks=pa.Check.between(0, 100),
        ),
        # Steadman/NWS heat index in Celsius derived from temperature and humidity.
        "heat_idx_c": pa.Column(float, nullable=False, coerce=True),
    },
    strict=True,
    unique=["kabupaten_code", "date"],
)

# Generated by code/data/10_fetch_temperature_gee.py -> data/generated/daily_temperature_kab.parquet
# Row level: one kabupaten-day weather record with heat features, keyed by kabupaten_code + date.
DAILY_TEMPERATURE_HEAT_SCHEMA = pa.DataFrameSchema(
    {
        # Base daily weather columns from DAILY_TEMPERATURE_SCHEMA.
        **DAILY_TEMPERATURE_SCHEMA.columns,
        # Indicator that daily maximum temperature is at least 28 C.
        "hot28": _binary_column(),
        # Indicator that daily maximum temperature is at least 30 C.
        "hot30": _binary_column(),
        # Indicator that daily maximum temperature is at least 32 C.
        "hot32": _binary_column(),
        # Count of hot28 days in the current and previous 6 days.
        "hot28_7d": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=False, coerce=True
        ),
        # Count of hot28 days in the current and previous 29 days.
        "hot28_30d": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        # Count of hot30 days in the current and previous 6 days.
        "hot30_7d": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=False, coerce=True
        ),
        # Count of hot30 days in the current and previous 29 days.
        "hot30_30d": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        # Count of hot32 days in the current and previous 6 days.
        "hot32_7d": pa.Column(
            float, checks=pa.Check.between(0, 7), nullable=False, coerce=True
        ),
        # Count of hot32 days in the current and previous 29 days.
        "hot32_30d": pa.Column(
            float, checks=pa.Check.between(0, 30), nullable=False, coerce=True
        ),
        # Cooling degree days using 22 C as the base temperature.
        "cdd": pa.Column(float, checks=pa.Check.ge(0), nullable=False, coerce=True),
        # Seven-day rolling sum of cooling degree days.
        "cdd_7d": pa.Column(float, checks=pa.Check.ge(0), nullable=False, coerce=True),
        # Rolling 30-day kabupaten-specific 90th percentile of mean temperature.
        "tmean_p90_30d": pa.Column(float, nullable=True, coerce=True),
        # Indicator that mean temperature is at least the kabupaten p90 over the pulled window.
        "is_extreme": _binary_column(),
    },
    strict=True,
    unique=["kabupaten_code", "date"],
)

# Generated by code/data/08_fetch_aod_gee.py -> data/generated/aod_monthly_kab.parquet
# Row level: one kabupaten-month aerosol record, keyed by kabupaten_code + year + month.
AOD_MONTHLY_SCHEMA = pa.DataFrameSchema(
    {
        # BPS four-digit kabupaten code identifying the polygon.
        "kabupaten_code": pa.Column(int, nullable=False, coerce=True),
        # Calendar year of the MODIS monthly aerosol observation.
        "year": pa.Column(
            int, checks=pa.Check.between(1900, 2100), nullable=False, coerce=True
        ),
        # Calendar month of the MODIS monthly aerosol observation.
        "month": pa.Column(
            int, checks=pa.Check.between(1, 12), nullable=False, coerce=True
        ),
        # MODIS 550 nm aerosol optical depth, scaled to physical units.
        "aod": pa.Column(float, checks=pa.Check.ge(0), nullable=True, coerce=True),
    },
    strict=True,
    unique=["kabupaten_code", "year", "month"],
)

# Generated by code/data/09_fetch_merra_pm25.py -> data/generated/pm25_daily_kab.parquet
# Row level: one kabupaten-day PM2.5 record, keyed by kabupaten_code + date.
PM25_DAILY_SCHEMA = pa.DataFrameSchema(
    {
        # BPS four-digit kabupaten code identifying the polygon.
        "kabupaten_code": pa.Column(int, nullable=False, coerce=True),
        # Calendar date of the daily MERRA-2 aerosol aggregate.
        "date": pa.Column(pa.DateTime, nullable=False, coerce=True),
        # Estimated PM2.5 concentration in micrograms per cubic meter.
        "pm25_ugm3": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # MERRA-2 black-carbon surface aerosol mass mixing ratio component.
        "BCSMASS": pa.Column(float, checks=pa.Check.ge(0), nullable=True, coerce=True),
        # MERRA-2 organic-carbon surface aerosol mass mixing ratio component.
        "OCSMASS": pa.Column(float, checks=pa.Check.ge(0), nullable=True, coerce=True),
        # MERRA-2 sulfate surface aerosol mass mixing ratio component.
        "SO4SMASS": pa.Column(float, checks=pa.Check.ge(0), nullable=True, coerce=True),
        # MERRA-2 fine dust surface aerosol mass mixing ratio component.
        "DUSMASS25": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # MERRA-2 fine sea-salt surface aerosol mass mixing ratio component.
        "SSSMASS25": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
    },
    strict=True,
    unique=["kabupaten_code", "date"],
)

# Generated by code/data/20_build_economic_exposures.py -> data/generated/20_economic_exposures.parquet
# Row level: one person-wave economic exposure record, keyed by pidlink + wave.
ECONOMIC_EXPOSURES_SCHEMA = pa.DataFrameSchema(
    {
        # Stable IFLS person identifier, used as the person-level merge key.
        "pidlink": _id_column(),
        # IFLS survey wave for the economic exposure record.
        "wave": _wave_column(),
        # Respondent had at least one job termination in the past 5 years.
        "recent_job_loss_5y": _binary_column(),
        # Last job termination reason was fired, laid off, or plant closure.
        "involuntary_loss_5y": _binary_column(),
        # Days between interview date and the last reported job termination date.
        "days_since_last_loss": pa.Column(float, nullable=True, coerce=True),
        # Last job termination occurred within 365 days before interview.
        "job_loss_within_yr": _binary_column(),
        # Household owns a vehicle.
        "vehicle_owner": _binary_column(),
        # Household is in an urban area according to the screening file.
        "urban": _binary_column(),
        # Household received a cash-transfer benefit or held a BLT card.
        "cash_transfer_recipient": _binary_column(),
        # Household held a BLT cash-transfer card.
        "blt_card": _binary_column(),
        # Household held a health insurance or health assistance card.
        "health_card": _binary_column(),
        # Household province is in the Sumatra/Kalimantan palm-oil region.
        "palm_region": _binary_column(),
        # World Bank monthly palm-oil price for the interview month, USD/MT.
        "palm_price_usd_mt": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Z-score of the interview-month palm-oil price over the script's price history.
        "palm_price_z": pa.Column(float, nullable=True, coerce=True),
        # Low palm-price exposure: palm region times the negative part of palm_price_z.
        "palm_shock": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
    },
    strict=True,
    unique=["pidlink", "wave"],
)

# Generated by code/data/25_build_commodity_transport_exposures.py -> data/generated/25_commodity_transport_exposures.parquet
# Row level: one person-wave commodity/transport exposure record, keyed by pidlink + wave.
COMMODITY_TRANSPORT_EXPOSURES_SCHEMA = pa.DataFrameSchema(
    {
        # Stable IFLS person identifier, used as the person-level merge key.
        "pidlink": _id_column(),
        # IFLS survey wave for the refined shock record.
        "wave": _wave_column(),
        # Respondent works in agriculture according to the 1-digit sector code.
        "agricultural": _binary_column(nullable=True),
        # Household province is in the Sumatra/Kalimantan palm-oil region.
        "palm_region": _binary_column(),
        # Respondent is agricultural and lives in a palm-oil region.
        "palm_farmer_individual": _binary_column(),
        # Any household member is flagged as a palm farmer in that wave.
        "palm_farmer_hh": _binary_column(),
        # Household province is in a major rubber-producing region.
        "rubber_region": _binary_column(),
        # Respondent is agricultural and lives in a rubber-producing region.
        "rubber_farmer_individual": _binary_column(),
        # Household province is in a major coffee-producing region.
        "coffee_region": _binary_column(),
        # Respondent is agricultural and lives in a coffee-producing region.
        "coffee_farmer_individual": _binary_column(),
        # Monthly household transportation spending.
        "transport_spending_mo": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        # Total monthly household spending used as the transport-share denominator.
        "total_mo": pa.Column(float, checks=pa.Check.ge(0), nullable=True, coerce=True),
        # Transportation spending divided by total monthly household spending.
        "transport_share": pa.Column(
            float, checks=pa.Check.between(0, 1), nullable=True, coerce=True
        ),
        # Within-wave quintile of transport_share.
        "transport_share_q5": pa.Column(
            float, checks=pa.Check.between(1, 5), nullable=True, coerce=True
        ),
        # Indicator for the top within-wave quintile of transport_share.
        "high_transport_share": _binary_column(),
    },
    strict=True,
    unique=["pidlink", "wave"],
)

# Generated by code/data/11_build_health_exposures.py -> data/generated/health_bereavement_shocks.parquet
# Row level: one person-wave health/bereavement shock record, keyed by pidlink + wave.
HEALTH_BEREAVEMENT_SHOCKS_SCHEMA = pa.DataFrameSchema(
    {
        # Stable IFLS person identifier, used as the person-level merge key.
        "pidlink": _id_column(),
        # Count of recent acute symptoms reported in the past 4 weeks.
        "n_symptoms": pa.Column(
            int, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        # Indicator for at least 5 recent acute symptoms.
        "many_symptoms": _binary_column(),
        # IFLS survey wave for the health/bereavement shock record.
        "wave": _wave_column(),
        # Respondent reported any inpatient hospitalization in the past 12 months.
        "recent_hospitalised": _binary_column(),
        # Respondent had a treated accident within 2 years before interview.
        "recent_accident_2y": _binary_column(),
        # Respondent became widowed within 5 years before interview.
        "recently_widowed_5y": _binary_column(),
    },
    strict=True,
    unique=["pidlink", "wave"],
)

# Generated by code/data/12_build_finance_distress.py -> data/generated/finance_distress_shocks.parquet
# Row level: one person-wave financial-distress record, keyed by pidlink + wave.
FINANCE_DISTRESS_SHOCKS_SCHEMA = pa.DataFrameSchema(
    {
        # Stable IFLS person identifier, used as the person-level merge key.
        "pidlink": _id_column(),
        # IFLS survey wave for the financial-distress shock record.
        "wave": _wave_column(),
        # Wave-specific household identifier used for household-level merges.
        "hhid": _id_column(),
        # Household debt proxy; IFLS5 is loan stock, IFLS4 is recent loan flow.
        "debt": pa.Column(float, checks=pa.Check.ge(0), nullable=False, coerce=True),
        # Household is in the top quartile of positive debt within wave.
        "debt_q4": _binary_column(),
        # Respondent's summed inpatient out-of-pocket medical spending.
        "med_oop": pa.Column(float, checks=pa.Check.ge(0), nullable=False, coerce=True),
        # Respondent is in the top quartile of positive medical OOP spending within wave.
        "high_med_oop": _binary_column(),
    },
    strict=True,
    unique=["pidlink", "wave"],
)

# Core columns built inside code/data/13_build_analysis_table_input.py before adding
# model/table-specific variables.
ANALYSIS_BASE_COLUMNS = {
    **INDIVIDUALS_SCHEMA.columns,
    **_schema_columns(
        CESD_SCORES_SCHEMA,
        ["cesd_raw", "cesd10_count", "depressed", "n_items"],
    ),
    **_schema_columns(
        STRESSORS_SCHEMA,
        [
            "age",
            "sex",
            "married",
            "widowed",
            "edu_yrs",
            "hhsize",
            "pce",
            "pce_log",
            "pce_quintile",
            "disaster_5yr",
            "disaster_severe_5yr",
            "loan_rejected",
            "agri_occupation",
        ],
    ),
    # Final analysis sample is restricted to adults with non-missing age.
    "age": pa.Column(
        float, checks=pa.Check.between(15, 120), nullable=False, coerce=True
    ),
    **_schema_columns(
        DAILY_TEMPERATURE_HEAT_SCHEMA,
        ["tmean_c", "tmax_c", "tmin_c", "heat_idx_c", "rh_pct", "precip_mm"],
    ),
    # Final builder clips small negative ERA5 precipitation artifacts to zero.
    "precip_mm": pa.Column(float, checks=pa.Check.ge(0), nullable=False, coerce=True),
    # Mean temperature one day before interview.
    "tmean_lag1": pa.Column(float, nullable=True, coerce=True),
    # Mean temperature averaged over the prior 3 days, excluding interview day.
    "tmean_lag3": pa.Column(float, nullable=True, coerce=True),
    # Mean temperature averaged over the prior 7 days, excluding interview day.
    "tmean_lag7": pa.Column(float, nullable=True, coerce=True),
    # Minimum temperature one day before interview.
    "tmin_lag1": pa.Column(float, nullable=True, coerce=True),
    # Maximum temperature one day before interview.
    "tmax_lag1": pa.Column(float, nullable=True, coerce=True),
    # Heat index one day before interview.
    "heat_idx_lag1": pa.Column(float, nullable=True, coerce=True),
    # Mean temperature averaged over the prior 30 days, excluding interview day.
    "tmean_base30": pa.Column(float, nullable=True, coerce=True),
    # Mean temperature 7 days after interview, used as a placebo lead.
    "tmean_lead7": pa.Column(float, nullable=True, coerce=True),
    # Interview-day mean temperature minus the prior-30-day baseline.
    "t_anom_today": pa.Column(float, nullable=True, coerce=True),
    # One-day lagged mean temperature minus the prior-30-day baseline.
    "t_anom_lag1": pa.Column(float, nullable=True, coerce=True),
    # Indicator for interviews after Indonesia's 2014 fuel-subsidy reform date.
    "post_subsidy": _binary_column(),
    # Indicator for interviews during the 2015 haze episode in affected months/regions.
    "haze_2015": _binary_column(),
    # IFLS4 indicator for provinces in the Yogyakarta earthquake catchment.
    "yogya_quake_catchment": _binary_column(),
    # Interview-day mean-temperature bin for non-linear heat specifications.
    "heat_bin": pa.Column(
        str,
        checks=pa.Check.isin(["<22", "22-24", "24-26", "26-28", "28+"]),
        nullable=False,
        coerce=True,
    ),
    # Interview month-year string for monthly fixed effects.
    "month_year": pa.Column(str, nullable=False, coerce=True),
    # Calendar month of interview.
    "month": pa.Column(
        int, checks=pa.Check.between(1, 12), nullable=False, coerce=True
    ),
    # Calendar year of interview.
    "year": pa.Column(
        int, checks=pa.Check.between(1900, 2100), nullable=False, coerce=True
    ),
}

# Generated by code/data/12_fetch_temperature_hourly_gee.py -> data/generated/hourly_temperature_kab.parquet
# Row level: one kabupaten-hour weather record, keyed by kabupaten_code + datetime_utc.
HOURLY_TEMPERATURE_SCHEMA = pa.DataFrameSchema(
    {
        # BPS four-digit kabupaten code identifying the polygon.
        "kabupaten_code": pa.Column(int, nullable=False, coerce=True),
        # UTC timestamp of the hourly ERA5-Land observation.
        "datetime_utc": pa.Column(pa.DateTime, nullable=False, coerce=True),
        # Hourly polygon-mean 2m air temperature in Celsius.
        "tmean_c_hour": pa.Column(float, nullable=False, coerce=True),
        # Hourly polygon-mean 2m dewpoint temperature in Celsius.
        "dewp_c_hour": pa.Column(float, nullable=True, coerce=True),
    },
    strict=True,
    unique=["kabupaten_code", "datetime_utc"],
)

# Generated by code/data/13_build_analysis_table_input.py -> data/generated/analysis_table_input.parquet
# Row level: one canonical person-wave analysis record, keyed by pidlink + wave.
ANALYSIS_TABLE_INPUT_SCHEMA = pa.DataFrameSchema(
    {
        **ANALYSIS_BASE_COLUMNS,
        # Female indicator used by the table/regression controls.
        "female": _binary_column(),
        # CES-D total standardized within wave for pooled IFLS4/IFLS5 specifications.
        "cesd_z": pa.Column(float, nullable=False, coerce=True),
        # Mean-centered daily temperature variables used in interaction models.
        "heat_c_dev": pa.Column(float, nullable=False, coerce=True),
        "tmean_c_dev": pa.Column(float, nullable=False, coerce=True),
        "tmax_c_dev": pa.Column(float, nullable=False, coerce=True),
        "tmin_c_dev": pa.Column(float, nullable=False, coerce=True),
        # Cooling-degree-day threshold variables used by Table 2.
        "cdd_tmax30": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        "cdd_tmax32": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        "cdd_tmin23": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        "cdd_tmin24": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        **ECONOMIC_EXPOSURES_SCHEMA.columns,
        # Commodity/transport exposure variables retained in the analysis table.
        **_schema_columns(
            COMMODITY_TRANSPORT_EXPOSURES_SCHEMA,
            [
                "palm_farmer_individual",
                "palm_farmer_hh",
                "rubber_farmer_individual",
                "coffee_farmer_individual",
                "transport_share",
            ],
        ),
        # Interview month tuple pieces and derived shock variables.
        "palm_3mo_decline": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        "palm_shock": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        "fuel_shock": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "rubber_price_usd_kg": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "rubber_price_z": pa.Column(float, nullable=True, coerce=True),
        "rubber_shock": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        "coffee_price_clb": pa.Column(
            float, checks=pa.Check.ge(0), nullable=True, coerce=True
        ),
        "coffee_price_z": pa.Column(float, nullable=True, coerce=True),
        "coffee_shock": pa.Column(
            float, checks=pa.Check.ge(0), nullable=False, coerce=True
        ),
        # CES-D factor scores and within-wave standardized versions.
        **_schema_columns(
            CESD_SCORES_SCHEMA,
            [
                "somatic",
                "depraffect",
                "posaffect",
                "somatic_z",
                "depraffect_z",
                "posaffect_z",
            ],
        ),
        # Keep old CES-D score artifacts readable while 24 owns factor construction.
        "somatic": pa.Column(float, checks=pa.Check.ge(0), nullable=True, coerce=True),
        "somatic_z": pa.Column(float, nullable=True, coerce=True),
        # Optional exploratory sidecar variables, filled with zeros when sidecars are absent.
        **HEALTH_BEREAVEMENT_SHOCKS_SCHEMA.columns,
        **_schema_columns(FINANCE_DISTRESS_SHOCKS_SCHEMA, ["debt_q4", "high_med_oop"]),
        "pce_decline_q4": _binary_column(),
    },
    strict=True,
    unique=["pidlink", "wave"],
)
